/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 회원가입
     * @description 아이디, 비밀번호, 이름, 이메일, 나이를 입력받아 회원가입합니다.
     */
    post: operations["signUp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/signin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그인
     * @description 아이디와 비밀번호로 로그인합니다. 이후 API 호출에 사용할 userId를 반환합니다.
     */
    post: operations["signIn"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 개인정보 조회
     * @description userId로 특정 유저의 개인정보를 조회합니다.
     */
    get: operations["getUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 개인정보 수정
     * @description userId로 특정 유저의 이름, 이메일, 나이를 수정합니다.
     */
    patch: operations["updateUser"];
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 유저 목록 조회
     * @description 최근 가입한 유저 20명의 ID, 이름, 파트를 조회합니다.
     */
    get: operations["getUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 회원가입 요청 */
    SignUpRequest: {
      /**
       * @description 로그인 아이디 (4~20자)
       * @example sopt_user
       */
      loginId: string;
      /**
       * @description 비밀번호 (8~20자)
       * @example password123
       */
      password: string;
      /**
       * @description 이름 (10자 이하)
       * @example 홍길동
       */
      name: string;
      /**
       * Format: email
       * @description 이메일
       * @example sopt@sopt.org
       */
      email: string;
      /**
       * Format: int32
       * @description 나이 (1~150)
       * @example 25
       */
      age?: number;
      /**
       * @description 파트 (iOS, 안드로이드, 웹)
       * @example iOS
       * @enum {string}
       */
      part: "iOS" | "안드로이드" | "웹";
    };
    /** @description 공통 응답 형식 */
    ApiResponse: {
      /** @description 성공 여부 */
      success?: boolean;
      /**
       * Format: int32
       * @description HTTP 상태 코드
       * @example 200
       */
      status?: number;
      /**
       * @description 응답 메시지
       * @example OK
       */
      message?: string;
      /**
       * @description 에러 코드
       * @example USER_404_001
       */
      code?: string;
      /** @description 응답 데이터 */
      data?: unknown;
      /** @description 에러 메타 정보 */
      meta?: components["schemas"]["Meta"];
    };
    Meta: {
      path?: string;
      timestamp?: string;
    };
    /** @description 로그인 요청 */
    SignInRequest: {
      /**
       * @description 로그인 아이디
       * @example sopt_user
       */
      loginId?: string;
      /**
       * @description 비밀번호
       * @example password123
       */
      password?: string;
    };
    /** @description 개인정보 수정 요청 */
    UserUpdateRequest: {
      /**
       * @description 변경할 이름
       * @example 김철수
       */
      name?: string;
      /**
       * @description 변경할 이메일
       * @example new@sopt.org
       */
      email?: string;
      /**
       * Format: int32
       * @description 변경할 나이
       * @example 26
       */
      age?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      /** @description 회원가입 성공 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
      /** @description 유효하지 않은 파트 값 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description 이미 사용 중인 아이디 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description 로그인 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
      /** @description 존재하지 않는 아이디 또는 비밀번호 불일치 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 유저 ID
         * @example 1
         */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
      /** @description 존재하지 않는 유저 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 수정할 유저 ID
         * @example 1
         */
        userId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateRequest"];
      };
    };
    responses: {
      /** @description 수정 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
      /** @description 존재하지 않는 유저 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  getUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
}
